env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals: {}
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  no-restricted-syntax:
    - off
  no-plusplus:
    - off
